### ISSUE TITLE
MSGraphClientFactory.serviceKey Uncaught ReferenceError: MSGraphClientFactory is not defined

### ISSUE THREAD

**Issue by Ofer-Gal** [mmsharepoint/react-teams-graph-upload-as-pdf#1]
I am not sure if I missed a step but I installed in the Workbench and I follow the code after the file drop and after line 7 in graphService.ts, nothing happens. 
Checking the MSGraphClientFactory.serviceKey  I get error: 
`Uncaught ReferenceError: MSGraphClientFactory is not defined`

Never mind. the:
```
   "webApiPermissionRequests": [
      {
        "resource": "Microsoft Graph",
        "scope": "Files.ReadWrite"
      },     
      {
        "resource": "Microsoft Graph",
        "scope": "Sites.ReadWrite.All"
      }
    ]

```
did not make a request so I went to Azure and gave admin consent on both of this and it worked.
Thank you for a great sample.

**Comment by mmsharepoint** [comment]
Indeed, when you need "new" permissions you always need to install the webpart in the app catalog first
OR
request and grant the permissions with PS for instance (a scenario I prefer in prod scenarios, but in demo repos like this I always put in the webApiPermissionRequests in the package-solution.json for documentation reasons at least ...

Great that you were able to solve on your own!

**Comment by Ofer-Gal** [comment]
Would it be too much to ask if I ask for addition to your sample where I could see uploading a large file to a SharePoint library not in the root of the tenant (/sites/something).
I did look at your Outlook example but could not figure out how to change it to SPFx  

Thank you in advance

**Comment by mmsharepoint** [comment]
Well the Outlook sample IS SPFx so not much to change here.
The root or not of the tenant does not really matter, you need the driveID to specify your target.
Then you establish a session on behalf of your Grapg client as I did here:
https://github.com/mmsharepoint/ReactOutlook2SP_SPFx/blob/master/src/controller/GraphController.ts#L174-L195
And from there you upload the slices as much as you have depending on the whole size and how you split it (x320kb)
https://github.com/mmsharepoint/ReactOutlook2SP_SPFx/blob/master/src/controller/GraphController.ts#L197-L215

**Comment by Ofer-Gal** [comment]
thank you
