### ISSUE TITLE
SPFx Web Part Samples

### ISSUE THREAD

**Issue by hugoabernier** [mmsharepoint/react-teams-graph-upload-as-pdf#2]
Hey @mmsharepoint, I was just reviewing some of the old PnP videos and noticed that we don't have this amazing sample in our PnP repo.

Would you be interested in having your web part listed in the PnP repo? We'd take a snapshot of the code -- nothing for you to do. Of course, we'd give you credit for your work!

Let me know. Just @ me here, or feel free to reach out via Twitter or LinkedIn!

Thanks again for doing awesome work!

**Comment by mmsharepoint** [comment]
Hi @hugoabernier,
indeed I can also submit this sample as a PR to your repo:
Let me first polish the README
and I am also thinking about bringing it to the latest version, shouldn't be hard with the cli, right?

I think "I forgot" to submit those days in favor of my parallel (but not yet demoed) Teams Tab sample:
(https://github.com/pnp/teams-dev-samples/tree/main/samples/tab-sso-graph-upload-as-pdf)
The up- and download "ping-pong" server-side is a bit more robust ...

Anyway, will work on the PR this week. Promised!

**Comment by mmsharepoint** [comment]
@hugoabernier Faster than expected: A PR was just submitted with an upgraded version :-)
